spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/nakup-product
    username: postgres
    password: zxca


jpa:
  hibernate:
    ddl-auto: update

server:
  port: 8093

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    app-name: product-service
    instance-id: ${spring.application.name}:${random.value}

